### ISSUE TITLE
Make delete skins message a lil more user friendly

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/storefront-pro-skins#6]
![screen shot 2017-11-08 at 13 51 27](https://user-images.githubusercontent.com/3070779/32552515-1d151a24-c48c-11e7-8a62-80981f7a652f.png)

**Comment by shramee** [comment]
Looking like this now ;)

![image](https://user-images.githubusercontent.com/11048263/33273867-87612634-d3b4-11e7-9df1-cfd829232e69.png)
