### ISSUE TITLE
Make 'save skin' modal a bit clearer that it's a modal

### ISSUE THREAD

**Issue by jamiemarsland** [pootlepress/storefront-pro-skins#7]
it gets lost a lil - how about we put it in a modal box

![screen shot 2017-11-26 at 09 20 23](https://user-images.githubusercontent.com/3070779/33238725-28cf689e-d28b-11e7-8032-8271fdeedf87.png)

**Comment by shramee** [comment]
Added **Save skin** title ;)

![image](https://user-images.githubusercontent.com/11048263/33273916-b2205d90-d3b4-11e7-9f5f-6b8881f6f886.png)
